apiVersion: v1
kind: Service
metadata:
  name: digitalocean-demo-lb
spec:
  type: LoadBalancer
  selector:
    app: digitalocean-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
